global:
  scrape_interval: 15s

scrape_configs:
  - job_name: eventservice
    static_configs:
      - targets: ["eventservice:8080"]
    metrics_path: /metrics

  - job_name: bookingservice
    static_configs:
      - targets: ["bookingservice:8080"]
    metrics_path: /metrics

  - job_name: authservice
    static_configs:
      - targets: ["authservice:8080"]
    metrics_path: /metrics 